use crate::types::{Category, Severity};
use regex::Regex;

#[allow(dead_code)]
#[derive(Clone)]
pub struct Rule {
    pub id: String,
    pub cwe: String,
    pub severity: Severity,
    pub confidence: String,
    pub sources: Vec<String>,
    pub sinks: Vec<String>,
    pub sanitizers: Vec<String>,
    pub description: String,
    pub recommendation: String,
    pub name: String,
    pub category: Category,
    pub pattern: Regex,
}

impl Rule {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        id: &str,
        name: &str,
        category: Category,
        severity: Severity,
        confidence: &str,
        cwe: &str,
        sources: &[&str],
        sinks: &[&str],
        sanitizers: &[&str],
        pattern: Regex,
        description: &str,
        recommendation: &str,
    ) -> Self {
        Self {
            id: id.to_string(),
            name: name.to_string(),
            category,
            severity,
            confidence: confidence.to_string(),
            cwe: cwe.to_string(),
            sources: sources.iter().map(|s| s.to_string()).collect(),
            sinks: sinks.iter().map(|s| s.to_string()).collect(),
            sanitizers: sanitizers.iter().map(|s| s.to_string()).collect(),
            pattern,
            description: description.to_string(),
            recommendation: recommendation.to_string(),
        }
    }
}

pub fn get_sast_rules() -> Vec<Rule> {
    vec![
        Rule::new(
            "VG-SAST-001",
            "Potential SQL Injection",
            Category::SourceCode,
            Severity::HIGH,
            "HIGH",
            "CWE-89",
            &["request.args", "request.form", "req.query", "r.URL.Query", "user_input"],
            &["db.execute", "cursor.execute", "sql.Query", "SELECT", "INSERT", "UPDATE", "DELETE"],
            &["int", "float", "strconv.Atoi", "parameterized binding"],
            Regex::new(r#"(?i)(f["'].*\b(SELECT\s+[\s\S]+?\s+FROM|INSERT\s+INTO|UPDATE\s+\w+\s+SET|DELETE\s+FROM|DROP\s+TABLE|UNION\s+(?:ALL\s+)?SELECT)\b.*\{|["'].*\b(SELECT\s+[\s\S]+?\s+FROM|INSERT\s+INTO|UPDATE\s+\w+\s+SET|DELETE\s+FROM)\b.*["']\s*\+|query.*\+.*request|execute\(["'].*%\s*|execute\(["'].*\{\}.*\.format|execute\(f["']|\bfmt\.Sprintf\(["'].*\b(SELECT\s+[\s\S]+?\s+FROM|INSERT\s+INTO|UPDATE\s+\w+\s+SET|DELETE\s+FROM)\b|`.*\b(SELECT\s+[\s\S]+?\s+FROM|INSERT\s+INTO|UPDATE\s+\w+\s+SET|DELETE\s+FROM)\b.*\$\{)"#).unwrap(),
            "Potential SQL injection vulnerability detected via dynamic query construction.",
            "Use parameterized queries, prepared statements, or ORM parameter binding.",
        ),
        Rule::new(
            "VG-SAST-002",
            "Potential OS Command Injection",
            Category::SourceCode,
            Severity::HIGH,
            "HIGH",
            "CWE-78",
            &["request.args", "req.body", "user_input", "sys.argv"],
            &["os.system", "os.popen", "subprocess.run", "subprocess.Popen", "exec.Command", "child_process.exec"],
            &["shlex.quote", "argument array without shell"],
            Regex::new(r#"(?i)(exec\.Command\(|os\.system\(|os\.popen\(|subprocess\.(call|check_output|run|Popen)\(|child_process\.(exec|spawn)\(|Runtime\.getRuntime\(\)\.exec\()"#).unwrap(),
            "Potential OS command injection vulnerability detected.",
            "Avoid executing OS commands with untrusted input. Use safe parameter lists without a shell.",
        ),
        Rule::new(
            "VG-SAST-003",
            "Dangerous Eval",
            Category::SourceCode,
            Severity::HIGH,
            "HIGH",
            "CWE-95",
            &["user_input", "request_payload"],
            &["eval", "Function", "exec"],
            &["json.loads", "JSON.parse"],
            Regex::new(r#"(?i)\b(eval\(|Function\(|exec\()"#).unwrap(),
            "Use of dangerous dynamic code evaluation functions detected.",
            "Avoid using eval or dynamic code execution on untrusted input.",
        ),
        Rule::new(
            "VG-SAST-004",
            "Potential TLS Misconfiguration",
            Category::SourceCode,
            Severity::HIGH,
            "HIGH",
            "CWE-295",
            &["tls_options", "config"],
            &["verify=False", "InsecureSkipVerify: true", "rejectUnauthorized: false"],
            &["trusted_ca_bundle", "strict verification"],
            Regex::new(r#"(?i)(InsecureSkipVerify.*true|verify.*False|rejectUnauthorized.*false|NODE_TLS_REJECT_UNAUTHORIZED)"#).unwrap(),
            "TLS certificate verification seems to be disabled.",
            "Enable strict TLS certificate verification in production environments.",
        ),
        Rule::new(
            "VG-SAST-005",
            "Weak Crypto",
            Category::SourceCode,
            Severity::MEDIUM,
            "MEDIUM",
            "CWE-327",
            &["source_code"],
            &["hashlib.md5", "hashlib.sha1", "DES.new", "Math.random"],
            &["SHA-256", "AES-GCM", "crypto/rand"],
            Regex::new(r#"(?i)\b(md5|sha1|DES|RC4)\b|Math\.random\(\)"#).unwrap(),
            "Weak cryptographic algorithm or non-cryptographic PRNG detected.",
            "Use modern algorithms (e.g., SHA-256, AES-GCM) and cryptographically secure PRNGs.",
        ),
        Rule::new(
            "VG-SAST-006",
            "Potential Insecure HTTP Connection",
            Category::SourceCode,
            Severity::MEDIUM,
            "MEDIUM",
            "CWE-319",
            &["url_constant", "network_call"],
            &["http://"],
            &["https://", "localhost", "127.0.0.1"],
            Regex::new(r#"http://[^\s"'>]+"#).unwrap(),
            "Insecure plaintext HTTP connection detected.",
            "Use HTTPS for all network communication.",
        ),
        Rule::new(
            "VG-SAST-007",
            "Hardcoded Credentials",
            Category::SourceCode,
            Severity::HIGH,
            "HIGH",
            "CWE-798",
            &["source_code"],
            &["password = \"...\""],
            &["os.environ", "secrets_manager"],
            Regex::new(r#"(?i)password\s*=\s*"[^"]+""#).unwrap(),
            "Hardcoded credentials discovered in source code.",
            "Use environment variables or a secret management service.",
        ),
        Rule::new(
            "VG-SAST-008",
            "Shell Execution With Potentially Untrusted Input",
            Category::SourceCode,
            Severity::HIGH,
            "HIGH",
            "CWE-78",
            &["user_input", "request_args"],
            &["subprocess.run(shell=True)", "subprocess.Popen(shell=True)"],
            &["shell=False", "shlex.quote"],
            Regex::new(r#"(?i)\b(shell\s*=\s*True|shell\s*=\s*1)\b"#).unwrap(),
            "Subprocess invocation with shell=True detected. If untrusted input reaches this command, it enables arbitrary shell execution.",
            "Set shell=False and pass command arguments as an array/list of strings.",
        ),
        Rule::new(
            "VG-AUTH-001",
            "Weak Password Hashing Algorithm",
            Category::SourceCode,
            Severity::HIGH,
            "HIGH",
            "CWE-916",
            &["user_password"],
            &["hashlib.md5", "hashlib.sha1"],
            &["bcrypt", "Argon2id", "scrypt", "PBKDF2"],
            Regex::new(r#"(?i)(hashlib\.(md5|sha1)\(.*(password|passwd|pwd)|(md5|sha1)\(.*(password|passwd|pwd))"#).unwrap(),
            "MD5 or SHA-1 is being used to hash passwords. These algorithms are vulnerable to high-speed collision and dictionary attacks.",
            "Use modern password hashing algorithms such as Argon2id, bcrypt, scrypt, or PBKDF2.",
        ),
        Rule::new(
            "VG-AUTH-002",
            "Predictable Security Token",
            Category::SourceCode,
            Severity::HIGH,
            "HIGH",
            "CWE-330",
            &["email", "username", "timestamp"],
            &["base64.b64encode", "urlsafe_b64encode"],
            &["secrets.token_urlsafe", "crypto/rand"],
            Regex::new(r#"(?i)(base64\.(b64encode|urlsafe_b64encode)\(.*(email|user_id|username|user\.)|(email|username)\.encode\(\).*(base64|b64encode)|(token|reset_token)\s*=\s*.*(username|email).*\+.*(timestamp|time))"#).unwrap(),
            "Predictable or reversible encoding (such as base64 over email/user data) used as an authentication or reset token. Encoding does not provide cryptographic randomness.",
            "Generate password reset and session tokens using cryptographically secure random generators (e.g., secrets.token_urlsafe).",
        ),
        Rule::new(
            "VG-AUTH-003",
            "Hardcoded Authentication Token",
            Category::Secret,
            Severity::HIGH,
            "HIGH",
            "CWE-798",
            &["source_code"],
            &["Authorization: Bearer", "ADMIN_TOKEN", "JWT_SECRET"],
            &["os.environ", "secrets_vault"],
            Regex::new(r#"(?i)(Authorization:\s*Bearer\s+[A-Za-z0-9._~+/-]{10,}|(ADMIN_TOKEN|BEARER_TOKEN|SESSION_TOKEN)\s*=\s*['"](?:Bearer\s+)?[A-Za-z0-9._~+/-]{12,}['"]|JWT_SECRET\s*[:=]\s*['"][^'"]{8,}['"])"#).unwrap(),
            "Hardcoded Bearer authentication token or JWT secret detected in code.",
            "Retrieve bearer tokens and JWT secrets at runtime from environment variables or a vault.",
        ),
    ]
}

pub fn get_secret_rules() -> Vec<Rule> {
    vec![
        Rule::new(
            "VG-SEC-001",
            "AWS Access Key",
            Category::Secret,
            Severity::CRITICAL,
            "HIGH",
            "CWE-798",
            &["source_code", "config"],
            &["hardcoded credential"],
            &["IAM roles", "AWS Secrets Manager"],
            Regex::new(r#"AKIA[0-9A-Z]{16}"#).unwrap(),
            "AWS Access Key ID detected.",
            "Revoke the key immediately and use IAM roles instead.",
        ),
        Rule::new(
            "VG-SEC-002",
            "Generic API Key",
            Category::Secret,
            Severity::CRITICAL,
            "HIGH",
            "CWE-798",
            &["source_code", "config"],
            &["api_key assignment"],
            &["environment variables", "vault"],
            Regex::new(r#"(?i)(api[_-]?key|apikey)\s*[:=]\s*['"][^'"]{8,}"#).unwrap(),
            "Generic API Key detected.",
            "Remove the key from code and use a secret manager.",
        ),
        Rule::new(
            "VG-SEC-003",
            "GitHub Token",
            Category::Secret,
            Severity::CRITICAL,
            "HIGH",
            "CWE-798",
            &["source_code", "git config"],
            &["ghp_ token"],
            &["GitHub Secrets", "SSH deploy keys"],
            Regex::new(r#"ghp_[a-zA-Z0-9]{36}"#).unwrap(),
            "GitHub Personal Access Token detected.",
            "Revoke the token and generate a new one if needed.",
        ),
        Rule::new(
            "VG-SEC-004",
            "Slack Token",
            Category::Secret,
            Severity::CRITICAL,
            "HIGH",
            "CWE-798",
            &["source_code", "config"],
            &["xox token"],
            &["Slack App credentials in vault"],
            Regex::new(r#"xox[bprs]-[a-zA-Z0-9-]+"#).unwrap(),
            "Slack Token detected.",
            "Revoke and rotate the Slack token.",
        ),
        Rule::new(
            "VG-SEC-005",
            "Private Key",
            Category::Secret,
            Severity::CRITICAL,
            "HIGH",
            "CWE-798",
            &["source_code", "repo file"],
            &["RSA/DSA/EC PRIVATE KEY"],
            &["KMS", "vault", "SSH agent"],
            Regex::new(r#"-----BEGIN\s+(RSA|DSA|EC|OPENSSH)?\s*PRIVATE KEY-----"#).unwrap(),
            "Private cryptographic key detected.",
            "Remove private keys from the repository.",
        ),
        Rule::new(
            "VG-SEC-006",
            "Password Assignment",
            Category::Secret,
            Severity::CRITICAL,
            "HIGH",
            "CWE-798",
            &["source_code", "config"],
            &["password = '...'"],
            &["environment variables"],
            Regex::new(r#"(?i)(password|passwd|pwd)\s*[:=]\s*['"][^'"]+['"]"#).unwrap(),
            "Hardcoded password assignment detected.",
            "Use environment variables for passwords.",
        ),
        Rule::new(
            "VG-SEC-007",
            "Token/Secret Assignment",
            Category::Secret,
            Severity::CRITICAL,
            "HIGH",
            "CWE-798",
            &["source_code", "config"],
            &["token = '...'"],
            &["runtime secrets manager"],
            Regex::new(r#"(?i)(token|secret|jwt_secret)\s*[:=]\s*['"][^'"]{8,}['"]"#).unwrap(),
            "Hardcoded token or secret assignment detected.",
            "Move secrets to secure storage or environment variables.",
        ),
        Rule::new(
            "VG-SEC-008",
            "Generic Credential",
            Category::Secret,
            Severity::CRITICAL,
            "HIGH",
            "CWE-798",
            &["source_code", "config"],
            &["credential = '...'"],
            &["external vault"],
            Regex::new(r#"(?i)(secret|credential)\s*[:=]\s*['"][^'"]{8,}['"]"#).unwrap(),
            "Generic secret or credential detected.",
            "Securely manage all credentials outside of source control.",
        ),
    ]
}

pub fn rule_cwe(rule_id: &str) -> Option<&'static str> {
    match rule_id {
        "VG-SAST-001" => Some("CWE-89"),
        "VG-SAST-002" | "VG-SAST-008" => Some("CWE-78"),
        "VG-SAST-003" => Some("CWE-95"),
        "VG-SAST-004" => Some("CWE-295"),
        "VG-SAST-005" => Some("CWE-327"),
        "VG-SAST-006" => Some("CWE-319"),
        "VG-SAST-007" | "VG-AUTH-003" | "VG-SEC-001" | "VG-SEC-002" | "VG-SEC-003"
        | "VG-SEC-004" | "VG-SEC-005" | "VG-SEC-006" | "VG-SEC-007" | "VG-SEC-008"
        | "VG-SECRET-001" | "VG-SECRET-002" | "VG-SECRET-003" | "VG-GIT-001" => Some("CWE-798"),
        "VG-AUTH-001" => Some("CWE-916"),
        "VG-AUTH-002" => Some("CWE-330"),
        "VG-WEBHOOK-001" | "VG-DCK-005" => Some("CWE-345"),
        "VG-DCK-001" | "VG-DCK-004" | "VG-DCK-008" | "VG-DCK-011" | "VG-DCK-012" | "VG-DCK-013"
        | "VG-DCK-015" => Some("CWE-250"),
        "VG-DCK-002" => Some("CWE-214"),
        "VG-DCK-006" | "VG-DCK-007" | "VG-DCK-016" => Some("CWE-668"),
        "VG-DCK-009" => Some("CWE-552"),
        "VG-DCK-010" => Some("CWE-259"),
        "VG-DCK-003" | "VG-DCK-014" | "VG-CFG-004" | "VG-SECRET-FILE" => Some("CWE-200"),
        "VG-CFG-001" => Some("CWE-489"),
        "VG-CFG-002" => Some("CWE-942"),
        "VG-CFG-003" => Some("CWE-668"),
        "VG-CFG-005" => Some("CWE-319"),
        _ => None,
    }
}
